### ISSUE TITLE
[UserVoice 3.1.0]There come up duplicate ideas after cancelling Post an idea.

### ISSUE THREAD

**Issue by grainzh** [uservoice/uservoice-ios-sdk#287] opened 2014-05-27 07:52 UTC
This issue can also be found in UserVoice 3.03

Steps:
1. Go to Feedback page and choose Feedback Forum.
2. Tap on “Post an idea” button.
3. Tap on “Cancel” icon immediately after entering post an idea page.
4. Scroll down forum page and check the ideas.

Actual result: 
There are duplicate ideas in one page.

Expect result: 
There shouldn’t have any duplicate idea.

![image](https://cloud.githubusercontent.com/assets/6858557/3088664/d0b6c66e-e573-11e3-8d63-cf14c4f49f07.png)

**Comment by austintaylor** [comment] 2015-07-09 20:40
Still can't reproduce. Is it possible this was fixed by 4dfeb581 (a similar issue that occurred on the iPad)?

**Closed by austintaylor** 2015-07-09 20:40 UTC
